server:
  port: 8005
spring:
  application:
    name: myuserconsumer
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/ #,http://root:ok@localhost:7002/eureka/,http://root:ok@localhost:7003/eureka/
  instance:
    instance-id: myuserconsumer8005
    prefer-ip-address: true

feign:
  hystrix:
    enabled: false

myorderprovider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
